## Wektory atomiczne

Podstawowy typ danych: wektor atomiczny

przypisanie: operator `=` lub `<-`

`length(x)` - długość wektora

In [3]:
x=c(1,2,3)  # najprostszy sposób deklaracji wektora, za pomocą funkcji c
print(x)
print(class(x))
x2=c("a","b","c","d")
print(class(x2))
length(x)
length(x2)
length(3.14)   #taka liczba to też wektor ( z długością 1)
x3=3.14
x3==3.14  # wektor wartości logicznych
x2 == c("c","c","c","d")


[1] 1 2 3
[1] "numeric"
[1] "character"


[1] 3

[1] 4

[1] 1

[1] TRUE

[1] FALSE FALSE  TRUE  TRUE

Funkcja `c`  generalnie służy do łączenia (konkatenacji, `c`oncatenation). Pisząc `i:j` możemy tworzyć wektor zawierający liczby od `i` do `j` włącznie.

In [3]:
x1<- c(1,2,3)
x3<- 4:8
big_x<- c(x1,x3)
print(x1)
print(x3)
print(big_x)

[1] 1 2 3
[1] 4 5 6 7 8
[1] 1 2 3 4 5 6 7 8


## Listy
Lista różni się od wektora atomicznego- może zawierać różne typy danych, w tym inne listy (dość podobna do listy w Pythonie). Listę można indeksować tak jak wektor.

In [9]:
list_1<- list(1, "a", "b", 2, list(1,1,2))

In [10]:
length(list_1)

list_1[4:5]

[1] 5

[[1]]
[1] 2

[[2]]
[[2]][[1]]
[1] 1

[[2]][[2]]
[1] 1

[[2]][[3]]
[1] 2

### Lista z nazwanymi elementami

In [13]:
named_l<- list(a1=3, b2=222, trzeci=c(1,2,3))
print(named_l)

$a1
[1] 3

$b2
[1] 222

$trzeci
[1] 1 2 3



In [14]:
names(named_l)

[1] "a1"     "b2"     "trzeci"

In [15]:
named_l[["trzeci"]]
named_l[["a1"]]

[1] 1 2 3

[1] 3

In [16]:
names(named_l)<- c("nowa nazwa1", "nowa nazwa2", "nowa nazwa 3")
print(named_l)

$`nowa nazwa1`
[1] 3

$`nowa nazwa2`
[1] 222

$`nowa nazwa 3`
[1] 1 2 3



## Indeksowanie, 2 sposoby

`x[[i]]` - zawsze zwróci `i`-ty element `x`

`x[i]` - zwróci `i`-ty element `x` w "opakowaniu" (dla `x` wektora atomicznegp będzie to wektor atomiczny, ale dla dla listy- zwróci listę z jednym elementem)

In [2]:

x2= list("a","b","c")
x2[[3]]
x2[3]

[1] FALSE FALSE  TRUE  TRUE

[1] "c"

[[1]]
[1] "c"

### Indeksowanie wektorów i list

`x[[i]]` -- weź tylko element na pozycji $i$

`x[i]` -- weź element na pozycji $i$ z opakowaniem (dla wektora atomicznego, będzie to nadal wektor atomiczny, dla listy- lista z jednym elementem)

`x[i:j]` -- weź elementy od `i` do `j` opakowane np. listę od i do j, jeżeli x jest listą.

In [11]:
list_1[1]
list_1[[1]]


[[1]]
[1] 1

[1] 1

In [12]:
print(list_1)
print("podlista elementów list_1 od 4 do 5")
list_1[4:5]

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] "b"

[[4]]
[1] 2

[[5]]
[[5]][[1]]
[1] 1

[[5]][[2]]
[1] 1

[[5]][[3]]
[1] 2


[1] "podlista elementów list_1 od 4 do 5"


[[1]]
[1] 2

[[2]]
[[2]][[1]]
[1] 1

[[2]][[2]]
[1] 1

[[2]][[3]]
[1] 2

Wektory wartości logicznych mogą służyć do indeksowania (poniżej- tylko element z indeksem nr 3). Indeksować poprzez wektor wartości logicznych można zarówno listy jak i wektory atomiczne (jak i struktury wielowymiarowe).

In [4]:
x_logical= c(FALSE,FALSE,TRUE,FALSE,
             FALSE,FALSE,FALSE,FALSE)

big_x[x_logical]

[1] 3

test logiczny na wektorze wytworzy wektor wartości logicznych (testowany jest warunek element-po-elemencie)

In [5]:
print(big_x < 4)
logical_test<- (big_x < 4)
big_x[logical_test] #wybierz te elementy które są mniejsze od 4
big_x_reversed<- rev(big_x)  # funkcja rev <- odwraca wektor
print(big_x)
print(big_x_reversed)
print(big_x < big_x_reversed)

[1]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE


[1] 1 2 3

[1] 1 2 3 4 5 6 7 8
[1] 8 7 6 5 4 3 2 1
[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE


## operator %in%

In [6]:
1 %in% c(2:10)
1 %in% c(1:10)

[1] FALSE

[1] TRUE

## Wartości brakujące

In [9]:
#test czy x jest NULL
# NULL to odpowiednik None z Pythona
X<-NULL


In [10]:
is.null(X) # dobrze

[1] TRUE

In [11]:
X== NULL # ŹLE

logical(0)

In [12]:
#NA <- wartość brakująca, zazwyczaj oznacza BRAK DANYCH w wektorze liczbowym
vec_n<- c(1,2,NA)
is.na(vec_n)

[1] FALSE FALSE  TRUE

In [13]:
is.na(vec_n) # dobrze

[1] FALSE FALSE  TRUE

In [14]:
vec_n == NA # ŹLE

[1] NA NA NA

## funkcje, pętle i instrukcje warunkowe w R

In [17]:
funkcja1<- function(x1, x2)
    {
        if (length(x1)!= length(x2)) stop("nie można wykonać następnego testu bo długości x1 i x2 się różnią")
        if (sum(x1 == x2)==length(x1) ) # x1 == x2 <- wektor wartości logicznych TRUE FALSE
            {                           # sum(x1==x2) <- suma wartości TRUE FALSE (TRUE zamieniamy na 1, FALSE na 0)
                                        # sum(x1==x2) == length(x1) <- TRUE, tylko gdy są 3 wartości TRUE,
                                        # czyli x1 i x2 są równe na każdej pozycji.
            print(" x1 i x2 są równe")
            print("coś")
            return(c(1,2,3))
            }
        else
            {
            #print(seq_along(x)
            for (j in seq_along(x)) #seq_along(x) <- wektor wszystkich indeksów jakie ma x
                {
                print(x1[j])}
            return(c(4,5,6))
            
            }
                
            
    }

In [20]:
funkcja1(c(1,2,3),c(1,2,4))

[1] 1
[1] 2
[1] 3


[1] 4 5 6

#### seq_along

In [19]:
v1<-c()
print(seq_along(v1))
v1<-c(7,6,78)
seq_along(v1)

integer(0)


[1] 1 2 3

#### rep

In [15]:
rep(c("a","b"),2)
rep(c("a","b"),each=4)

[1] "a" "b" "a" "b"

[1] "a" "a" "a" "a" "b" "b" "b" "b"

### lapply

`lapply(x, fun, opcjonalne.fun.arg1, opcjonalne.fun.arg2... etc)` - zastosuj funkcję `fun` na każdym elemencie `x` (element-po-elemencie), opcjonalnie z argumentami `opcjonalnie.fun.arg1`, itd... Wyniki wsadź do listy o takiej samej długości co `x`.

Funkcje `apply` oraz `sapply` działają podobnie, ale istotne dla `lapply` jest to, że ZAWSZE zwraca listę, zatem łatwo ogarnąć jej stosowanie. 

In [18]:
list_1
lapply(list_1, rep, 3) # dla kazdego elementu list_1, wykonaj rep z argumentem 3 i wsadz wyniki do listy

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] "b"

[[4]]
[1] 2

[[5]]
[[5]][[1]]
[1] 1

[[5]][[2]]
[1] 1

[[5]][[3]]
[1] 2

[[1]]
[1] 1 1 1

[[2]]
[1] "a" "a" "a"

[[3]]
[1] "b" "b" "b"

[[4]]
[1] 2 2 2

[[5]]
[[5]][[1]]
[1] 1

[[5]][[2]]
[1] 1

[[5]][[3]]
[1] 2

[[5]][[4]]
[1] 1

[[5]][[5]]
[1] 1

[[5]][[6]]
[1] 2

[[5]][[7]]
[1] 1

[[5]][[8]]
[1] 1

[[5]][[9]]
[1] 2

In [22]:
V1<- c("a","b","c","d")
V1list<-lapply(V1, rep, 2 )
print(V1list)
V1listunlisted<- unlist(V1list)
print(V1listunlisted)

[[1]]
[1] "a" "a"

[[2]]
[1] "b" "b"

[[3]]
[1] "c" "c"

[[4]]
[1] "d" "d"

[1] "a" "a" "b" "b" "c" "c" "d" "d"


### Inne przydatne funkcje

In [38]:
X<-runif(1000) #1000 liczb losowych z zakresu [0,1]
median(X)            #== quantile(X,0.5)
quantile(X,0.25)

[1] 0.5284934

25% 
0.2415679

# Struktury 2D

## Data frame (ramka danych)

Pod spodem to lista wektorów tej samej długości, a interpretacja i zamysł jest taki- że to po prostu tablica 2D, gdzie różne kolumny mogą przechowywać różne typy danych. Wtedy, jeden wiersz statystycznie rzecz biorąc opisuje zazwyczaj jedną obserwację, kolumny- poszczególne zmienne.

In [16]:
df<-read.csv("https://europepmc.org/journalList?format=csv") # z poprzednich zajęć z artykułami
dim(df) # obiekt 2 wymiarowy 
# n_wierszy n_kolumn

[1] 3911   13

In [17]:
#indeksujemy każdy wymiar z osobna po przecinku:
df[1:5,1:5] #wiersze od 1 do 5 i kolumny od 1 do 5

Journal.title              NLM.TA             pISSN     eISSN    
1 3 Biotech                  3 Biotech          2190-572X 2190-5738
2 3D Printing in Medicine    3D Print Med                 2365-6271
3 AACE Clinical Case Reports AACE Clin Case Rep           2376-0605
4 The AAPS Journal           AAPS J                       1550-7416
5 AAPS PharmSci              AAPS PharmSci                1522-1059
  Publisher                                        
1 Springer                                         
2 BioMed Central                                   
3 American Association of Clinical Endocrinology   
4 American Association of Pharmaceutical Scientists
5 American Association of Pharmaceutical Scientists

In [18]:
df[1:5,] #wiersze od 1 do 5 i wszystkie kolumny

Journal.title              NLM.TA             pISSN     eISSN    
1 3 Biotech                  3 Biotech          2190-572X 2190-5738
2 3D Printing in Medicine    3D Print Med                 2365-6271
3 AACE Clinical Case Reports AACE Clin Case Rep           2376-0605
4 The AAPS Journal           AAPS J                       1550-7416
5 AAPS PharmSci              AAPS PharmSci                1522-1059
  Publisher                                         LOCATORplus.ID
1 Springer                                          NA            
2 BioMed Central                                    NA            
3 American Association of Clinical Endocrinology    NA            
4 American Association of Pharmaceutical Scientists NA            
5 American Association of Pharmaceutical Scientists NA            
  Latest.issue        Earliest.volume Free.access Open.access
1 v.13(1);Jan 2023    v.1;2011        12 months   Some       
2 v.8;Dec 2022        v.2;2016        Immediate   All        
3 v.8(6);Nov-Dec 2022 v.5;2019        Immediate   Some       
4 v.18(3);May 2016    v.6;2004                    Some       
5 v.6(2);Jun 2004     v.1;1999        Immediate   No         
  Participation.level Deposit.status   Journal.URL                        
1  Full                                http://europepmc.org/journals/1936/
2  Full                                http://europepmc.org/journals/3552/
3  Full                                http://europepmc.org/journals/3762/
4  Full                No New Content  http://europepmc.org/journals/262/ 
5  Full                Predecessor     http://europepmc.org/journals/1196/

In [19]:
nrow(df)
ncol(df)

[1] 3911

[1] 13

In [20]:
kolumnaAccess<-df$Open.access # dostęp do kolumny poprzez nazwę, sposób I
unique(kolumnaAccess) # unikalne wartości w danym wektorze


[1] Some All  No  
Levels: All No Some

In [24]:
kolumnaAccess<-df[,"Open.access"] #sposób II
table(kolumnaAccess) # funkcja table <- podsumowanie
table(df$Open.access,    #wiersze- OpenAccess
     df$Deposit.status)  #kolumny- Deposit status
                         #komórki- zliczenia obserwacji, takich że Open.access== to po lewej, a Deposit.status== to u góry

kolumnaAccess
 All   No Some 
1938  379 1594 

      
             No New Content   Predecessor 
  All  1445              319           174
  No    134              129           116
  Some 1424              128            42

In [25]:
#data frame to pod spodem lista wetkorów, zatem można użyć funkcji lapply:
#   (kolumny to wektory)

lapply(df, length) # długość każdej kolumny == nrow(df)

$Journal.title
[1] 3911

$NLM.TA
[1] 3911

$pISSN
[1] 3911

$eISSN
[1] 3911

$Publisher
[1] 3911

$LOCATORplus.ID
[1] 3911

$Latest.issue
[1] 3911

$Earliest.volume
[1] 3911

$Free.access
[1] 3911

$Open.access
[1] 3911

$Participation.level
[1] 3911

$Deposit.status
[1] 3911

$Journal.URL
[1] 3911

### Funkcje apply i działające po kolumnach i wierszach (analogicznie do lapply)

In [26]:
#apply(Obiekt2D, nr_wymiaru, funkcja, opcjonalnie.pozostałe.argumenty.funkcji)
# nr_ymiaru = 1 <- po wierszach
# nr_wymiaru= 2 <- po kolumnach
result<-apply(df,2,unique)   # sprawdzamy unikalne elementy w każdej kolumnie
class(result)                # korzystając z apply- warto sprawdzić typ zwróconego obiektu
lapply(result, function(x) x[1:5])   #weź z każdego elementu result 5 pierwszych elementów

[1] "list"

$Journal.title
[1] "3 Biotech"                  "3D Printing in Medicine"   
[3] "AACE Clinical Case Reports" "The AAPS Journal"          
[5] "AAPS PharmSci"             

$NLM.TA
[1] "3 Biotech"          "3D Print Med"       "AACE Clin Case Rep"
[4] "AAPS J"             "AAPS PharmSci"     

$pISSN
[1] "2190-572X" ""          "2374-7943" "1672-9145" "0392-4203"

$eISSN
[1] "2190-5738" "2365-6271" "2376-0605" "1550-7416" "1522-1059"

$Publisher
[1] "Springer"                                         
[2] "BioMed Central"                                   
[3] "American Association of Clinical Endocrinology"   
[4] "American Association of Pharmaceutical Scientists"
[5] "African Academy of Sciences"                      

$LOCATORplus.ID
[1] NA NA NA NA NA

$Latest.issue
[1] "v.13(1);Jan 2023"    "v.8;Dec 2022"        "v.8(6);Nov-Dec 2022"
[4] "v.18(3);May 2016"    "v.6(2);Jun 2004"    

$Earliest.volume
[1] "v.1;2011" "v.2;2016" "v.5;2019" "v.6;2004" "v.1;1999"

$Free.access
[1] "12 months"         "Immediate"         ""                 
[4] "12 months or less" "6 months"         

$Open.access
[1] "Some" "All"  "No"   NA     NA    

$Participation.level
[1] " Full "          " NIH Portfolio " NA                NA               
[5] NA               

$Deposit.status
[1] " "                " No New Content " " Predecessor "    NA                
[5] NA                

$Journal.URL
[1] "http://europepmc.org/journals/1936/" "http://europepmc.org/journals/3552/"
[3] "http://europepmc.org/journals/3762/" "http://europepmc.org/journals/262/" 
[5] "http://europepmc.org/journals/1196/"

## Macierze

In [31]:
A<- matrix(c(1,2,3,4,5,6,7,8,9,10), nrow=2)
A

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [32]:
B<- rbind(c(1,2,3),
         c(2,3,4)) #rowbind
class(B)
B

[1] "matrix" "array"

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 2    3    4

In [33]:
dim(A)
dim(B)

[1] 2 5

[1] 2 3

In [34]:
apply(A,2,mean) # średnie po kolumnach (można też po dataframe jeżeli zawiera liczby)
#funkcje działające szybko:
print(A)
rowMeans(A)
colMeans(A)
print(B)
rowSums(B)
colSums(B)

[1] 1.5 3.5 5.5 7.5 9.5

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


[1] 5 6

[1] 1.5 3.5 5.5 7.5 9.5

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    3    4


[1] 6 9

[1] 3 5 7

In [35]:
B_transposed<- t(B) #transpozycja macierzy, funkcja t
print(B)
print(B_transposed)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    3    4
     [,1] [,2]
[1,]    1    2
[2,]    2    3
[3,]    3    4


In [36]:
B %*% B_transposed #mnożenie macierzy 2X3 %*% 3X2 = 2X2

[,1] [,2]
[1,] 14   20  
[2,] 20   29

In [37]:
BBt<-B %*% B_transposed
diag(BBt) # przekątna

[1] 14 29

## Funkcja t.test i korekta p.wartości

## Wykresy i wizualizacje